navbar_title = "Saeid Akhavan"
navbar_subtitle = "Data Science Journey"
footer = "Copyright © 2021-2023 by Saeid Akhavan Ghorbani"
author = "Saeid Akhavan Ghorbani"
color_scheme = "light"

enable_zooming_js = true
enable_toc = true
enable_site_search = true
enable_math = false

# SEO
enable_open_graph = true
enable_twitter_cards = true

# Collapsible Menu
enable_collapsible_toc = false
enable_collapsible_changelogs = true

[list_layout]
enable_group_by_year = true
enable_show_date = true
enable_pagination = false

# syntax highlight settings
[syntax_highlight]
lib = "prism.js" # "builtin" | "prism.js"

    [syntax_highlight.builtin]
    enable_code_copy = true

    [syntax_highlight.prism]
    enable_code_copy = true
    enable_line_no = false

# Add Google Fonts
[font_config]
    google_fonts = [
        ["Fira_Code", "400, 700"],
        ["Open Sans", "300, 400, 400i, 700, 700i"],
        ["Roboto", "100, 100i, 300, 300i, 400, 400i"],
        ["IBM Plex Sans", "100, 300, 300i"],
        ["IBM Plex Serif", "100, 300, 300i"],
        ["DM Serif Display", "100, 300, 300i"],
        ["Noto Sans", "100, 200, 300, 400"],
        ["Noto Serif", "100, 200, 300, 400"]
    ]

    brand = "Noto Sans"
    body = "Noto Serif"
    heading = "Noto Serif"
    footer = "Noto Sans"


