baseURL = "https://saeidakhavan.com/"
languageCode = "en-us"
title = "Saeid Akhavan's Data Science Journey"
theme = "hugo-theme-monochrome"

[params]
color_scheme = "dark" # "light" or "dark"

# Add Google Fonts
google_fonts = [
    ["Fira_Code", "400, 700"],
    ["Open_Sans", "400, 400i, 700, 700i"],
    ["Roboto", "100, 100i, 300, 300i, 400, 400i"],
    ["IBM_Plex_Sans", "100, 300, 300i"],
    ["DM Serif Display", "100, 300, 300i"]
]

brand_font = "DM Serif Display"
heading_font = "Roboto"
body_font = "Roboto"



[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "portfolio"
name = "portfolio"
url = "/portfolio/"
weight = 20

[[menu.main]]
identifier = "blog"
name = "blog"
url = "/blog/"
weight = 30

[[menu.main]]
identifier = "resume"
name = "resume"
url = "/file.pdf"
weight = 40

[[menu.main]]
identifier = "contact"
name = "contact"
url = "/contact/"
weight = 50

